# Gather summary stats for read alignments

# There are several ways to count the reads in the raw and trimmed files

# Option 1: wc -l  (Have to divide by 4)

# Option 2: grep, looking for specific symbols

# Option 3: Use the count data already generated by FASTQC/multiQC
